openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /userName/{name}:
    get:
      tags:
        - chatterbook-controller
      operationId: returnUser
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/User'
  /userList:
    get:
      tags:
        - chatterbook-controller
      operationId: returnUserList
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  /chatterPosts/{name}:
    get:
      tags:
        - chatterbook-controller
      operationId: returnChatterPosts
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChatterPost'
components:
  schemas:
    ChatterPost:
      type: object
      properties:
        chatterPost:
          type: string
    User:
      type: object
      properties:
        name:
          type: string
        chatterPosts:
          type: array
          items:
            $ref: '#/components/schemas/ChatterPost'
